### ISSUE TITLE
MSVC_DIA_SDK_DIR not set when using Visual Studio Community

### ISSUE THREAD

**Issue by pierricgimmig** [pierricgimmig/orbitprofiler#127]
The toolchain-windows files assume Visual Studio Professional is used to find the DIA SDK path.  When the Community edition is used, "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/DIA SDK" becomes "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/DIA SDK".

**Comment by beckerhe** [comment]
Hi Pierric,
what is your opinion on how we should deal with such a situation in general?

Currently the bootstrap file is not very sophisticated. It basically just assumes one
specific configuration, tries to build that and fails in any other case.

We could try to make the bootstrapping process smarter (detecting Visual Studio versions, maybe detecting locally installed versions of qt5, etc.),
but I fear that this might lead to a lot of maintenance work, because you usually have only
one setup available for testing and you probably won't even get close to covering all the
special cases (like installing VS on a different drive for example.) Probably CI won't help
us here either.

The toolchain files were intended to be just examples, or let's say templates. The developer
should adapt them to their needs. Making them smart would expose a lot of cmake machinery
to all the developers. I believe taking one of the templates and adjust them to their own needs
is possible for every developer with a general understanding of the C/C++ build model, but it
might get complicated if somebody is forced to debug a cmake script which tries to detect
different versions/editions of visual studio.

I personally don't believe in bootstrapping scripts. I try not to call them (in part because of security concerns) and I prefer a simple markdown document describing the build process (something like: 1. bootstrap vcpkg / 2. install packages a,b,c via vcpkg / 3. copy and adjust toolchain file / 4. configure with cmake / 5. build). I believe that spending time in making the build system simpler and more robust in general is more beneficial than maintaining a bootstrapping script.

But I know that several people on the team disagree with me on this and I know that there are also several good arguments for bootstrapping scripts. :-) That's why I'm interested what is your take on this.

Cheers,
Henning

**Comment by pierricgimmig** [comment]
Hi Henning, sorry for the delay.  I'd make sure the common cases are covered so that we offer a single step build process to the vast majority of users.  I see tremendous value in reducing friction for a new contributor.  Personally, I hate having to fight with the build system to compile a project.  If there is a way (and there must be) for us to make figure out what version of VS is installed, then why not do it and save people some time?  

I see the bootstrap script itself as documentation.  We're not forcing anyone to run it, but it's there for people who want a single-step build process.  Power users can inspect it to validate that every step is legit.

I find the script super useful as I'm constantly cloning the repo to make sure the build process works from scratch.  Having more that a single step would be really annoying and I'd end up writing a script anyway :-).  For automation and testing on different environments, it seems like having a single script to build and run is the way to go.

**Comment by beckerhe** [comment]
HI Pierric,
thank's for your feedback. I in particular like the idea of having a bootstrap file as some kind documentation where you can proof that it is correct.

But first things first. Regarding Visual Studio version and edition detection. The proper way to do that is to check the installation path(s) in the Windows Registry, then checking whether Visual C++ is enabled and which version, then deciding which compiler to use by default in case more than one is available. vcpkg has a powershell script doing that (with more than a hundred lines of code, if I remember correctly - that was why I was backing down on this topic). But we could try to integrate that powershell script since we depend on vcpkg anyway. The more complex part is probably to ensure that vcpkg chooses the same compiler as we do with the main project. At the moment this probably works either because MSVC offers binary compatibility in all versions of Visual C++ from VS2017 and VS2019 or out of pure luck.

Personally, I had quite bad experience with automatic detections and actions taken upon that (and we are seeing this right now, with freetype-gl linking against xrandr if the headers are in place, and with qt linking against glib if it detects its headers.). The gain was not worth the time. But maybe that's just me. 😅  Don't get me wrong. That's not a major issue at all for me. I'm perfectly fine going forward with a bootstrapping script. I just wanted to agree on a direction here.

Random thought which just came up: How do you feel about requiring git-bash? We could have one bootstrapping script for both Windows and Linux, but we won't be able to run it from cmd.exe on Windows.

**Comment by beckerhe** [comment]
This was (hopefully) resolved by https://github.com/pierricgimmig/orbitprofiler/pull/158
