### ISSUE TITLE
Orbit 1.0.2 does not like recursive functions

### ISSUE THREAD

**Issue by willll** [pierricgimmig/orbitprofiler#39]
I have the following code :
```
#include <iostream>
using namespace std;
int fib(int n)
{
	if (n <= 1)
		return n;
	return fib(n - 1) + fib(n - 2);
}

int main()
{
	for (auto i = 0; i < 10000000; i++) {
		int n = 20;
		cout << fib(n);
	}
	getchar();
	return 0;
}
```

(thanks https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/)

If I hook main and fib, I would expect to waste all my time in main, I don't, if I checked the live tab the main function did consume any time.
Moreover orbit crashed my exe.

**Comment by pierricgimmig** [comment]
The problem is not recursion, Orbit handles it.  The code you provided will be optimized into a single call to fib(20), then the stored value will be outputted multiple times.  In the image below, notice how the call to fib(20) is made *before* the for loop.

![fib_one_call](https://user-images.githubusercontent.com/3687222/53935610-e03ff400-405b-11e9-96d4-c17b3e36613d.png)

A way to prevent that compiler optimization is to use "static volatile int n = 20;" instead of "int n = 20".

![fib_multiple_calls](https://user-images.githubusercontent.com/3687222/53935630-f352c400-405b-11e9-8a58-c8e23d317718.png)

Compiling Release x64 on VS2015, I was able to capture the fib function.

![fib_orbit](https://user-images.githubusercontent.com/3687222/53935661-0e253880-405c-11e9-8e02-7aa369430428.png)

I couldn't reproduce the crash, but I'd like to know more.  What configuration were you compiling?  What version of Visual Studio?  Could you try turning "whole program optimizations" off?

Thanks for the code snippet by the way.

**Comment by willll** [comment]
Hi,

Prior to my test I disabled the optimization, , and the assembly code generated does not call fib before the loop :
![image](https://user-images.githubusercontent.com/464311/53962828-0300f580-40ba-11e9-85a0-3f1fa1098a64.png)
![image](https://user-images.githubusercontent.com/464311/53962944-42c7dd00-40ba-11e9-9bca-4b2d74f4c147.png)

And I was able to generate a call graph similar to yours, but my point was about :

![image](https://user-images.githubusercontent.com/464311/53964249-f500a400-40bc-11e9-86d7-a13e8c435da1.png)

main's total time should be at least equal to fib's total time, or did I missed something ?

Regarding to the crash, I am using VS2017 :

![image](https://user-images.githubusercontent.com/464311/53964810-00a09a80-40be-11e9-880e-307689020225.png)

I used the default debug configuration, but I disabled optimizations and I had to force /DEBUG:FULL to list the symbols in orbit.

![image](https://user-images.githubusercontent.com/464311/53964963-5117f800-40be-11e9-9ea3-f21ce6be0737.png)

If I run the program from visual studio in debug mode I have the following crash in the OrbitSendTimers thread (I did not noticed it at first because I using running my exe in cmd) :

![image](https://user-images.githubusercontent.com/464311/53965303-ef0bc280-40be-11e9-86d3-de5ff14c6bb8.png)

Hope this helps.

**Comment by pierricgimmig** [comment]
Hi, thanks for the clarification.

For a function to show up on the timeline, it has to be called after the capture starts and it has to return before the capture stops.  The main feature of Orbit is dynamic instrumentation.  What you see on the timeline are exact begin/end of function calls.  If a hook is installed after the function has been called, or if the function doesn't return before the capture ends, then the timing information will not be generated.

If you look at the sampling report however, you will see that "main" is indeed present in more samples than fib.

In order to see "main" on the timeline, you would have to use Orbit to launch your process, break at entry point, hook into "fib" and "main", start a capture and also make sure that the program finishes (that "main" actually returns) before stopping the capture.  It is definitely doable and quite a bit of work was put in to support hooking into main and even profile global initialization.

Thanks for the info about the crash, I'll definitely have a look when I have time.
