### ISSUE TITLE
OrbitQt.vcxproj has references to D:\git\Orbit

### ISSUE THREAD

**Issue by vvuk** [pierricgimmig/orbitprofiler#6]
Trying to build and ran into a few small problems:

The checked-in `OrbitQt.vcxproj` has absolute dir references to `D:\git\Orbit`, and `D:/git/Orbit`, as well as relative references to `..\..\Orbit` -- doing a straight string replace of those in the vcxproj file with `..` causes everything to build fine.

Also, `external/glew-1.13.0/lib` is missing -- glew needs to be rebuilt using the VS2015 toolchain from `glew-1.13.0/build/vc12`.

After fixing both of those, builds cleanly.  Happy to provide a patch/PR for OrbitQt.vcxproj if that'd be easier.

**Comment by pierricgimmig** [comment]
Thanks for reporting this.  I just submitted the glew-1.13.0 libs.  I'll switch to glew 2.0 soon.  I'd be happy to integrate your OrbitQt.vcxproj.  It's annoying, the Qt VS integration introduces hard coded paths in the vcxproj, I'll see if I can make it so that the paths are always relative.  Cheers!

**Comment by pierricgimmig** [comment]
Fixed in 305685bb83277aa36a92e928a048594c5f59ff85
